const {
  VITE_DOTENV,
  VITE_ONESIGNAL_APP_ID: ONESIGNAL_APP_ID,
  VITE_ONE_SIGNAL_API_KEY: ONE_SIGNAL_API_KEY,
  VITE_ONE_SIGNAL_USER_KEY: ONE_SIGNAL_USER_KEY
} = import.meta.env

const MOCKED_USER_ID = 'onesignal-wash-2024'

export {
  ONESIGNAL_APP_ID,
  ONE_SIGNAL_API_KEY,
  ONE_SIGNAL_USER_KEY,
  VITE_DOTENV as dotEnv,
  MOCKED_USER_ID
}
